version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    ports:
      - "8080:3000"
    volumes:
      - ../:/app
      - node_modules:/app/node_modules 
    command: npm run dev

volumes:
  node_modules: